swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
# The base URL for all API calls is defined using schemes, host and basePath
host: api.example.com
basePath: /v1
schemes:
  - https

definitions:
  User:
    properties:
      id:
        type: integer
      name:
        type: string
    # Both properties are required
    required:  
      - id
      - name

securityDefinitions:
  BasicAuth:
    type: basic
security:
  - BasicAuth: []

# The consumes and produces sections define the MIME types supported by the API. The root-level definition can be overridden in individual operations.
paths:
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - in: path
          name: userId
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
  /users:
    post:
      summary: Creates a new user.
      parameters:
        - in: body
          name: user
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: OK